/**
 * Food Safety Database
 *
 * Local database of foods and their safety criteria for a throat cancer patient
 * on a liquid/pureed diet undergoing radiation treatment.
 *
 * Each food is evaluated across six criteria:
 * 1. Acidity (pH) - foods below pH 5.0 flagged
 * 2. Texture - anything not completely smooth flagged
 * 3. Spice/Irritants - capsaicin, pepper, etc. flagged
 * 4. Temperature - very hot foods flagged as caution
 * 5. Osmolality - very salty/sugary foods flagged
 * 6. Alcohol - any alcohol content flagged
 *
 * DISCLAIMER: This is for informational purposes only. Always consult
 * qualified healthcare professionals before making dietary decisions.
 */

const foodDatabase = [
  // =========================================================================
  // FRUITS
  // =========================================================================
  {
    name: "Banana puree",
    aliases: ["banana", "bananas", "mashed banana"],
    category: "Fruits",
    verdict: "SAFE",
    criteria: {
      acidity: { flag: false, note: "pH ~5.0-5.3, low acidity" },
      texture: { flag: false, note: "Smooth when mashed or pureed" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Served at room temperature" },
      osmolality: { flag: false, note: "Moderate natural sugars" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: null,
  },
  {
    name: "Avocado",
    aliases: ["avocado", "guacamole", "mashed avocado"],
    category: "Fruits",
    verdict: "SAFE",
    criteria: {
      acidity: { flag: false, note: "pH ~6.3-6.6, neutral" },
      texture: { flag: false, note: "Creamy and smooth when mashed" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Served cool or room temperature" },
      osmolality: { flag: false, note: "Low osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: null,
  },
  {
    name: "Apple (cooked/peeled)",
    aliases: ["apple", "apples", "cooked apple", "apple puree", "stewed apple"],
    category: "Fruits",
    verdict: "CAUTION",
    criteria: {
      acidity: { flag: true, note: "pH ~3.3-4.0, moderately acidic" },
      texture: { flag: false, note: "Smooth when cooked and pureed" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Can be served cool" },
      osmolality: { flag: false, note: "Moderate natural sugars" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Cook thoroughly and puree until very smooth. Mix with oatmeal or yogurt to buffer acidity. Consider substituting with banana or pear puree.",
  },
  {
    name: "Mango puree",
    aliases: ["mango", "mangos", "mangoes", "mango puree"],
    category: "Fruits",
    verdict: "CAUTION",
    criteria: {
      acidity: { flag: true, note: "pH ~3.4-4.8, moderately acidic" },
      texture: { flag: false, note: "Smooth when pureed" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Served cool" },
      osmolality: { flag: true, note: "High natural sugar concentration" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Dilute with plain yogurt or oat milk to reduce acidity and sugar concentration. Use ripe mangoes only for softer texture.",
  },
  {
    name: "Peach puree",
    aliases: ["peach", "peaches", "peach puree"],
    category: "Fruits",
    verdict: "CAUTION",
    criteria: {
      acidity: { flag: true, note: "pH ~3.3-4.0, moderately acidic" },
      texture: { flag: false, note: "Smooth when pureed" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Served cool" },
      osmolality: { flag: false, note: "Moderate natural sugars" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Mix with plain yogurt or oatmeal to buffer acidity. Substitute with banana puree for a non-acidic option.",
  },
  {
    name: "Pear puree",
    aliases: ["pear", "pears", "cooked pear", "pear puree"],
    category: "Fruits",
    verdict: "SAFE",
    criteria: {
      acidity: { flag: false, note: "pH ~5.0-5.4, low acidity" },
      texture: { flag: false, note: "Very smooth when cooked and pureed" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Served cool or room temperature" },
      osmolality: { flag: false, note: "Moderate natural sugars" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: null,
  },
  {
    name: "Watermelon",
    aliases: ["watermelon", "watermelon juice"],
    category: "Fruits",
    verdict: "SAFE",
    criteria: {
      acidity: { flag: false, note: "pH ~5.2-5.6, low acidity" },
      texture: { flag: false, note: "Soft and juicy, easily pureed" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Served cool" },
      osmolality: { flag: false, note: "Low sugar concentration due to high water content" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: null,
  },
  {
    name: "Cantaloupe",
    aliases: ["cantaloupe", "rockmelon", "cantaloupe puree"],
    category: "Fruits",
    verdict: "SAFE",
    criteria: {
      acidity: { flag: false, note: "pH ~6.1-6.6, neutral" },
      texture: { flag: false, note: "Soft and easily pureed" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Served cool" },
      osmolality: { flag: false, note: "Moderate natural sugars" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: null,
  },
  {
    name: "Blueberry",
    aliases: ["blueberry", "blueberries", "blueberry puree"],
    category: "Fruits",
    verdict: "AVOID",
    criteria: {
      acidity: { flag: true, note: "pH ~3.1-3.4, acidic" },
      texture: { flag: true, note: "Skin fragments remain even when pureed" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Served cool" },
      osmolality: { flag: false, note: "Moderate natural sugars" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Substitute with banana puree or cooked pear puree for a smooth, non-acidic alternative.",
  },
  {
    name: "Strawberry",
    aliases: ["strawberry", "strawberries", "strawberry puree"],
    category: "Fruits",
    verdict: "AVOID",
    criteria: {
      acidity: { flag: true, note: "pH ~3.0-3.5, highly acidic" },
      texture: { flag: true, note: "Seeds remain even when pureed" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Served cool" },
      osmolality: { flag: false, note: "Moderate natural sugars" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Substitute with banana puree or mashed avocado for a smooth, non-acidic option.",
  },
  {
    name: "Raspberry",
    aliases: ["raspberry", "raspberries", "raspberry puree"],
    category: "Fruits",
    verdict: "AVOID",
    criteria: {
      acidity: { flag: true, note: "pH ~3.2-3.7, acidic" },
      texture: { flag: true, note: "Tiny seeds remain even when strained" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Served cool" },
      osmolality: { flag: false, note: "Moderate natural sugars" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Substitute with banana puree or cooked pear puree for a smooth, seed-free option.",
  },
  {
    name: "Orange",
    aliases: ["orange", "oranges", "orange juice", "oj"],
    category: "Fruits",
    verdict: "AVOID",
    criteria: {
      acidity: { flag: true, note: "pH ~3.0-4.0, highly acidic citrus" },
      texture: { flag: false, note: "Smooth when juiced" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Served cool" },
      osmolality: { flag: true, note: "High sugar concentration in juice form" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Substitute with diluted apple juice mixed with water, or try watermelon juice for a non-citrus option.",
  },
  {
    name: "Lemon",
    aliases: ["lemon", "lemons", "lemon juice", "lemonade"],
    category: "Fruits",
    verdict: "AVOID",
    criteria: {
      acidity: { flag: true, note: "pH ~2.0-2.6, extremely acidic" },
      texture: { flag: false, note: "Smooth when juiced" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Served cool" },
      osmolality: { flag: false, note: "Low sugar unless sweetened" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Avoid entirely. Use a pinch of salt or herbs for flavor instead of lemon.",
  },
  {
    name: "Lime",
    aliases: ["lime", "limes", "lime juice"],
    category: "Fruits",
    verdict: "AVOID",
    criteria: {
      acidity: { flag: true, note: "pH ~2.0-2.8, extremely acidic" },
      texture: { flag: false, note: "Smooth when juiced" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Served cool" },
      osmolality: { flag: false, note: "Low sugar" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: "Avoid entirely. Use mild herbs for seasoning instead.",
  },
  {
    name: "Grapefruit",
    aliases: ["grapefruit", "grapefruit juice"],
    category: "Fruits",
    verdict: "AVOID",
    criteria: {
      acidity: { flag: true, note: "pH ~3.0-3.8, highly acidic citrus" },
      texture: { flag: false, note: "Smooth when juiced" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Served cool" },
      osmolality: { flag: false, note: "Moderate sugar" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Substitute with cantaloupe or watermelon for a mild, non-acidic fruit option.",
  },
  {
    name: "Pineapple",
    aliases: ["pineapple", "pineapple juice", "pineapple puree"],
    category: "Fruits",
    verdict: "AVOID",
    criteria: {
      acidity: { flag: true, note: "pH ~3.2-4.0, acidic with bromelain enzyme" },
      texture: { flag: true, note: "Fibrous even when pureed" },
      spice: { flag: false, note: "No irritants but bromelain can cause irritation" },
      temperature: { flag: false, note: "Served cool" },
      osmolality: { flag: true, note: "High natural sugar concentration" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Avoid entirely. Try mango mixed with yogurt (less acidic) or banana puree instead.",
  },
  {
    name: "Cranberry",
    aliases: ["cranberry", "cranberries", "cranberry juice", "cranberry sauce"],
    category: "Fruits",
    verdict: "AVOID",
    criteria: {
      acidity: { flag: true, note: "pH ~2.3-2.5, extremely acidic" },
      texture: { flag: false, note: "Smooth when juiced or sauced" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Served cool" },
      osmolality: { flag: true, note: "Usually heavily sweetened, high osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Avoid entirely. Substitute with diluted pear juice or watermelon juice.",
  },
  {
    name: "Prune puree",
    aliases: ["prune", "prunes", "prune puree", "prune juice", "dried plum"],
    category: "Fruits",
    verdict: "AVOID",
    criteria: {
      acidity: { flag: true, note: "pH ~3.5-4.0, highly acidic" },
      texture: { flag: false, note: "Smooth when pureed" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Typically served cool" },
      osmolality: { flag: true, note: "High natural sugar concentration" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Substitute with banana puree or cooked pear puree for similar consistency without acidity.",
  },
  {
    name: "Grape",
    aliases: ["grape", "grapes", "grape juice"],
    category: "Fruits",
    verdict: "AVOID",
    criteria: {
      acidity: { flag: true, note: "pH ~3.5-4.5, moderately acidic" },
      texture: { flag: true, note: "Skin fragments when not juiced" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Served cool" },
      osmolality: { flag: true, note: "High natural sugar concentration" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Substitute with diluted pear juice or watermelon juice for a milder option.",
  },
  {
    name: "Cherry",
    aliases: ["cherry", "cherries", "cherry juice"],
    category: "Fruits",
    verdict: "AVOID",
    criteria: {
      acidity: { flag: true, note: "pH ~3.2-4.0, acidic" },
      texture: { flag: false, note: "Smooth when juiced" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Served cool" },
      osmolality: { flag: true, note: "High natural sugar" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Substitute with banana puree or cooked pear puree.",
  },
  {
    name: "Kiwi",
    aliases: ["kiwi", "kiwi fruit", "kiwifruit"],
    category: "Fruits",
    verdict: "AVOID",
    criteria: {
      acidity: { flag: true, note: "pH ~3.1-3.5, highly acidic" },
      texture: { flag: true, note: "Seeds remain even when pureed" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Served cool" },
      osmolality: { flag: false, note: "Moderate natural sugars" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Avoid entirely. Substitute with banana puree or cantaloupe puree.",
  },
  {
    name: "Papaya puree",
    aliases: ["papaya", "papayas", "papaya puree"],
    category: "Fruits",
    verdict: "SAFE",
    criteria: {
      acidity: { flag: false, note: "pH ~5.2-5.7, low acidity when ripe" },
      texture: { flag: false, note: "Very smooth when pureed" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Served cool" },
      osmolality: { flag: false, note: "Moderate natural sugars" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: null,
  },
  {
    name: "Coconut",
    aliases: ["coconut", "coconut cream", "coconut puree", "shredded coconut"],
    category: "Fruits",
    verdict: "CAUTION",
    criteria: {
      acidity: { flag: false, note: "pH ~6.0-7.0, neutral" },
      texture: { flag: true, note: "Shredded coconut has rough texture; use only coconut cream or milk" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Served cool" },
      osmolality: { flag: false, note: "Moderate" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Use coconut cream or coconut milk only — avoid shredded or flaked coconut. Coconut cream is smooth and soothing.",
  },

  // =========================================================================
  // VEGETABLES
  // =========================================================================
  {
    name: "Mashed potatoes",
    aliases: ["potato", "potatoes", "mashed potatoes", "mash potato", "mashed potato", "potato puree"],
    category: "Vegetables",
    verdict: "SAFE",
    criteria: {
      acidity: { flag: false, note: "pH ~5.4-5.9, neutral" },
      texture: { flag: false, note: "Smooth when properly mashed with butter/cream" },
      spice: { flag: false, note: "No irritants when plain" },
      temperature: { flag: false, note: "Serve warm, not hot" },
      osmolality: { flag: false, note: "Low osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: null,
  },
  {
    name: "Sweet potato puree",
    aliases: ["sweet potato", "sweet potatoes", "yam", "yams", "sweet potato puree"],
    category: "Vegetables",
    verdict: "SAFE",
    criteria: {
      acidity: { flag: false, note: "pH ~5.3-5.6, low acidity" },
      texture: { flag: false, note: "Very smooth when pureed with butter" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Serve warm, not hot" },
      osmolality: { flag: false, note: "Moderate natural sugars" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: null,
  },
  {
    name: "Butternut squash puree",
    aliases: ["butternut squash", "squash", "butternut", "squash puree"],
    category: "Vegetables",
    verdict: "SAFE",
    criteria: {
      acidity: { flag: false, note: "pH ~5.6-6.2, neutral" },
      texture: { flag: false, note: "Very smooth when cooked and pureed" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Serve warm, not hot" },
      osmolality: { flag: false, note: "Moderate natural sugars" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: null,
  },
  {
    name: "Acorn squash puree",
    aliases: ["acorn squash", "acorn squash puree"],
    category: "Vegetables",
    verdict: "SAFE",
    criteria: {
      acidity: { flag: false, note: "pH ~5.5-6.0, neutral" },
      texture: { flag: false, note: "Smooth when cooked and pureed" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Serve warm, not hot" },
      osmolality: { flag: false, note: "Low osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: null,
  },
  {
    name: "Carrot puree",
    aliases: ["carrot", "carrots", "carrot puree", "mashed carrots"],
    category: "Vegetables",
    verdict: "SAFE",
    criteria: {
      acidity: { flag: false, note: "pH ~5.9-6.4, neutral" },
      texture: { flag: false, note: "Smooth when cooked and pureed" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Serve warm, not hot" },
      osmolality: { flag: false, note: "Low osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: null,
  },
  {
    name: "Peas",
    aliases: ["peas", "pea", "green peas", "pea puree", "pea soup"],
    category: "Vegetables",
    verdict: "CAUTION",
    criteria: {
      acidity: { flag: false, note: "pH ~5.8-6.4, neutral" },
      texture: { flag: true, note: "Pea skins can be gritty even when pureed; strain after blending" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Serve warm, not hot" },
      osmolality: { flag: false, note: "Low osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Puree thoroughly and strain through a fine mesh sieve to remove skins. Mix with mashed potatoes for a smoother result.",
  },
  {
    name: "Green beans",
    aliases: ["green beans", "green bean", "string beans"],
    category: "Vegetables",
    verdict: "CAUTION",
    criteria: {
      acidity: { flag: false, note: "pH ~5.6-6.0, neutral" },
      texture: { flag: true, note: "Fibrous strings remain even when pureed" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Serve warm, not hot" },
      osmolality: { flag: false, note: "Low osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Cook until very soft, puree, and strain. Alternatively, substitute with carrot or squash puree.",
  },
  {
    name: "Broccoli",
    aliases: ["broccoli", "broccoli puree"],
    category: "Vegetables",
    verdict: "CAUTION",
    criteria: {
      acidity: { flag: false, note: "pH ~6.3-6.5, neutral" },
      texture: { flag: true, note: "Fibrous florets create grainy texture even when pureed" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Serve warm, not hot" },
      osmolality: { flag: false, note: "Low osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Cook until very soft, puree, and strain through fine mesh. Better to substitute with butternut squash or carrot puree.",
  },
  {
    name: "Cauliflower",
    aliases: ["cauliflower", "cauliflower puree", "mashed cauliflower"],
    category: "Vegetables",
    verdict: "SAFE",
    criteria: {
      acidity: { flag: false, note: "pH ~6.5-7.0, neutral" },
      texture: { flag: false, note: "Very smooth when cooked and pureed with butter" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Serve warm, not hot" },
      osmolality: { flag: false, note: "Low osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: null,
  },
  {
    name: "Spinach",
    aliases: ["spinach", "spinach puree", "creamed spinach"],
    category: "Vegetables",
    verdict: "CAUTION",
    criteria: {
      acidity: { flag: false, note: "pH ~5.5-6.8, neutral" },
      texture: { flag: true, note: "Fibrous leaves can be stringy; needs thorough blending" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Serve warm, not hot" },
      osmolality: { flag: false, note: "Low osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Cook thoroughly, puree in a high-speed blender, and strain. Mix into mashed potatoes or cream soup for better texture.",
  },
  {
    name: "Corn",
    aliases: ["corn", "sweet corn", "creamed corn", "corn puree"],
    category: "Vegetables",
    verdict: "CAUTION",
    criteria: {
      acidity: { flag: false, note: "pH ~5.9-6.3, neutral" },
      texture: { flag: true, note: "Corn hulls remain gritty even when pureed" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Serve warm, not hot" },
      osmolality: { flag: false, note: "Moderate natural sugars" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Only use creamed corn that is strained. Better to substitute with mashed potatoes or butternut squash puree.",
  },
  {
    name: "Zucchini puree",
    aliases: ["zucchini", "courgette", "zucchini puree"],
    category: "Vegetables",
    verdict: "SAFE",
    criteria: {
      acidity: { flag: false, note: "pH ~5.7-6.1, neutral" },
      texture: { flag: false, note: "Very smooth when cooked and pureed" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Serve warm, not hot" },
      osmolality: { flag: false, note: "Low osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: null,
  },
  {
    name: "Beet puree",
    aliases: ["beet", "beets", "beetroot", "beet puree"],
    category: "Vegetables",
    verdict: "SAFE",
    criteria: {
      acidity: { flag: false, note: "pH ~5.3-6.6, low acidity" },
      texture: { flag: false, note: "Smooth when cooked and pureed" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Serve warm or cool" },
      osmolality: { flag: false, note: "Moderate natural sugars" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: null,
  },
  {
    name: "Celery",
    aliases: ["celery", "celery juice", "celery puree"],
    category: "Vegetables",
    verdict: "CAUTION",
    criteria: {
      acidity: { flag: false, note: "pH ~5.7-6.0, neutral" },
      texture: { flag: true, note: "Very fibrous and stringy, difficult to puree smooth" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Served cool or warm" },
      osmolality: { flag: false, note: "Low osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Juice only and strain thoroughly. Better to use in soups that are fully blended and strained.",
  },
  {
    name: "Cucumber",
    aliases: ["cucumber", "cucumbers"],
    category: "Vegetables",
    verdict: "CAUTION",
    criteria: {
      acidity: { flag: false, note: "pH ~5.1-5.7, neutral" },
      texture: { flag: true, note: "Seeds and skin create texture; must be peeled, seeded, and pureed" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Served cool" },
      osmolality: { flag: false, note: "Low osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Peel, seed, and blend into a smooth puree. Consider mixing into yogurt for a cooling, smooth side.",
  },
  {
    name: "Tomato",
    aliases: ["tomato", "tomatoes", "tomato sauce", "tomato paste", "marinara"],
    category: "Vegetables",
    verdict: "AVOID",
    criteria: {
      acidity: { flag: true, note: "pH ~4.0-4.5, highly acidic" },
      texture: { flag: false, note: "Smooth when sauced" },
      spice: { flag: false, note: "No irritants (plain)" },
      temperature: { flag: false, note: "Varies" },
      osmolality: { flag: false, note: "Moderate" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Avoid all tomato products. Substitute with butternut squash sauce or cream-based sauces.",
  },
  {
    name: "Onion",
    aliases: ["onion", "onions", "raw onion", "cooked onion"],
    category: "Vegetables",
    verdict: "AVOID",
    criteria: {
      acidity: { flag: false, note: "pH ~5.3-5.8, neutral" },
      texture: { flag: false, note: "Smooth when cooked and pureed" },
      spice: { flag: true, note: "Contains sulfur compounds that irritate damaged tissue" },
      temperature: { flag: false, note: "Varies" },
      osmolality: { flag: false, note: "Low osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Avoid raw onion. Very small amounts of well-cooked, pureed onion in soups may be tolerated. Use with caution.",
  },
  {
    name: "Garlic",
    aliases: ["garlic", "raw garlic", "garlic powder"],
    category: "Vegetables",
    verdict: "AVOID",
    criteria: {
      acidity: { flag: false, note: "pH ~5.8, neutral" },
      texture: { flag: false, note: "Smooth when pureed" },
      spice: { flag: true, note: "Strong irritant, especially raw; allicin causes burning sensation" },
      temperature: { flag: false, note: "Varies" },
      osmolality: { flag: false, note: "Low osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Avoid raw garlic. Very small amounts of well-cooked garlic in cream soups may be tolerated. Use mild herbs like basil instead.",
  },
  {
    name: "Bell pepper",
    aliases: ["bell pepper", "bell peppers", "sweet pepper", "capsicum"],
    category: "Vegetables",
    verdict: "CAUTION",
    criteria: {
      acidity: { flag: true, note: "pH ~4.6-5.0, mildly acidic" },
      texture: { flag: true, note: "Skin is tough and does not puree well" },
      spice: { flag: false, note: "No capsaicin (sweet variety)" },
      temperature: { flag: false, note: "Varies" },
      osmolality: { flag: false, note: "Low osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "If used, roast until very soft, peel completely, and puree. Better to substitute with carrot or squash puree.",
  },

  // =========================================================================
  // PROTEINS
  // =========================================================================
  {
    name: "Chicken (pureed)",
    aliases: ["chicken", "chicken puree", "pureed chicken", "chicken breast", "chicken thigh"],
    category: "Proteins",
    verdict: "SAFE",
    criteria: {
      acidity: { flag: false, note: "pH ~5.8-6.2, neutral" },
      texture: { flag: false, note: "Smooth when cooked and pureed with broth" },
      spice: { flag: false, note: "No irritants when plain" },
      temperature: { flag: false, note: "Serve warm, not hot" },
      osmolality: { flag: false, note: "Low osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: null,
  },
  {
    name: "Turkey (pureed)",
    aliases: ["turkey", "turkey puree", "pureed turkey", "ground turkey"],
    category: "Proteins",
    verdict: "SAFE",
    criteria: {
      acidity: { flag: false, note: "pH ~5.7-6.2, neutral" },
      texture: { flag: false, note: "Smooth when cooked and pureed with broth" },
      spice: { flag: false, note: "No irritants when plain" },
      temperature: { flag: false, note: "Serve warm, not hot" },
      osmolality: { flag: false, note: "Low osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: null,
  },
  {
    name: "Beef (pureed)",
    aliases: ["beef", "beef puree", "pureed beef", "ground beef", "steak"],
    category: "Proteins",
    verdict: "CAUTION",
    criteria: {
      acidity: { flag: false, note: "pH ~5.4-5.8, neutral" },
      texture: { flag: true, note: "Can be fibrous and difficult to puree completely smooth" },
      spice: { flag: false, note: "No irritants when plain" },
      temperature: { flag: false, note: "Serve warm, not hot" },
      osmolality: { flag: false, note: "Low osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Use ground beef or slow-cooked beef, puree with broth until very smooth. Chicken or turkey puree is easier to get smooth.",
  },
  {
    name: "Pork (pureed)",
    aliases: ["pork", "pork puree", "pureed pork", "ground pork"],
    category: "Proteins",
    verdict: "CAUTION",
    criteria: {
      acidity: { flag: false, note: "pH ~5.4-5.7, neutral" },
      texture: { flag: true, note: "Can be fibrous; needs thorough cooking and pureeing" },
      spice: { flag: false, note: "No irritants when plain" },
      temperature: { flag: false, note: "Serve warm, not hot" },
      osmolality: { flag: false, note: "Low osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Slow-cook until falling apart, then puree with broth. Chicken or turkey puree may be easier.",
  },
  {
    name: "Salmon (pureed)",
    aliases: ["salmon", "salmon puree", "fish", "fish puree"],
    category: "Proteins",
    verdict: "SAFE",
    criteria: {
      acidity: { flag: false, note: "pH ~6.1-6.5, neutral" },
      texture: { flag: false, note: "Flaky and easily pureed when cooked" },
      spice: { flag: false, note: "No irritants when plain" },
      temperature: { flag: false, note: "Serve warm, not hot" },
      osmolality: { flag: false, note: "Low osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: null,
  },
  {
    name: "Tilapia (pureed)",
    aliases: ["tilapia", "tilapia puree"],
    category: "Proteins",
    verdict: "SAFE",
    criteria: {
      acidity: { flag: false, note: "pH ~6.0-6.5, neutral" },
      texture: { flag: false, note: "Mild and easily pureed" },
      spice: { flag: false, note: "No irritants when plain" },
      temperature: { flag: false, note: "Serve warm, not hot" },
      osmolality: { flag: false, note: "Low osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: null,
  },
  {
    name: "Cod (pureed)",
    aliases: ["cod", "cod puree"],
    category: "Proteins",
    verdict: "SAFE",
    criteria: {
      acidity: { flag: false, note: "pH ~6.0-6.5, neutral" },
      texture: { flag: false, note: "Flaky and easily pureed" },
      spice: { flag: false, note: "No irritants when plain" },
      temperature: { flag: false, note: "Serve warm, not hot" },
      osmolality: { flag: false, note: "Low osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: null,
  },
  {
    name: "Scrambled eggs",
    aliases: ["egg", "eggs", "scrambled eggs", "scrambled egg", "egg puree", "soft egg"],
    category: "Proteins",
    verdict: "SAFE",
    criteria: {
      acidity: { flag: false, note: "pH ~7.0-8.0, neutral to slightly alkaline" },
      texture: { flag: false, note: "Soft and smooth when scrambled soft or pureed" },
      spice: { flag: false, note: "No irritants when plain" },
      temperature: { flag: false, note: "Serve warm, not hot" },
      osmolality: { flag: false, note: "Low osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: null,
  },
  {
    name: "Tofu",
    aliases: ["tofu", "silken tofu", "soft tofu", "tofu puree"],
    category: "Proteins",
    verdict: "SAFE",
    criteria: {
      acidity: { flag: false, note: "pH ~7.0-7.2, neutral" },
      texture: { flag: false, note: "Silken tofu is very smooth" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Can be served cool or warm" },
      osmolality: { flag: false, note: "Low osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: null,
  },
  {
    name: "Black beans (pureed)",
    aliases: ["black beans", "black bean", "black bean puree", "refried beans"],
    category: "Proteins",
    verdict: "CAUTION",
    criteria: {
      acidity: { flag: false, note: "pH ~5.7-6.2, neutral" },
      texture: { flag: true, note: "Bean skins can be gritty; must be pureed and strained" },
      spice: { flag: false, note: "No irritants when plain" },
      temperature: { flag: false, note: "Serve warm, not hot" },
      osmolality: { flag: false, note: "Low osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Puree thoroughly and strain through fine mesh to remove skins. Refried beans (smooth, plain) may work. Add butter or sour cream for smoothness.",
  },
  {
    name: "Pinto beans (pureed)",
    aliases: ["pinto beans", "pinto bean", "pinto bean puree"],
    category: "Proteins",
    verdict: "CAUTION",
    criteria: {
      acidity: { flag: false, note: "pH ~5.8-6.2, neutral" },
      texture: { flag: true, note: "Bean skins can be gritty; must be pureed and strained" },
      spice: { flag: false, note: "No irritants when plain" },
      temperature: { flag: false, note: "Serve warm, not hot" },
      osmolality: { flag: false, note: "Low osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Puree thoroughly and strain through fine mesh. Smooth refried beans may work well.",
  },
  {
    name: "Kidney beans (pureed)",
    aliases: ["kidney beans", "kidney bean", "kidney bean puree"],
    category: "Proteins",
    verdict: "CAUTION",
    criteria: {
      acidity: { flag: false, note: "pH ~5.7-6.1, neutral" },
      texture: { flag: true, note: "Bean skins can be gritty; must be pureed and strained" },
      spice: { flag: false, note: "No irritants when plain" },
      temperature: { flag: false, note: "Serve warm, not hot" },
      osmolality: { flag: false, note: "Low osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Puree thoroughly and strain. Substitute with smooth hummus (without tahini seeds) or tofu puree.",
  },
  {
    name: "Lentils (pureed)",
    aliases: ["lentils", "lentil", "lentil puree", "lentil soup", "dal"],
    category: "Proteins",
    verdict: "CAUTION",
    criteria: {
      acidity: { flag: false, note: "pH ~6.0-6.8, neutral" },
      texture: { flag: true, note: "Red lentils puree smoothest; others can be gritty" },
      spice: { flag: false, note: "No irritants when plain" },
      temperature: { flag: false, note: "Serve warm, not hot" },
      osmolality: { flag: false, note: "Low osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Use red lentils — they break down most smoothly. Puree and strain. Serve as a smooth soup with butter.",
  },
  {
    name: "Shrimp (pureed)",
    aliases: ["shrimp", "shrimp puree", "prawns"],
    category: "Proteins",
    verdict: "SAFE",
    criteria: {
      acidity: { flag: false, note: "pH ~6.5-7.0, neutral" },
      texture: { flag: false, note: "Smooth when cooked and pureed" },
      spice: { flag: false, note: "No irritants when plain" },
      temperature: { flag: false, note: "Serve warm, not hot" },
      osmolality: { flag: false, note: "Low osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: null,
  },

  // =========================================================================
  // DAIRY & ALTERNATIVES
  // =========================================================================
  {
    name: "Milk",
    aliases: ["milk", "whole milk", "2% milk", "skim milk", "cow's milk"],
    category: "Dairy & Alternatives",
    verdict: "SAFE",
    criteria: {
      acidity: { flag: false, note: "pH ~6.5-6.8, neutral" },
      texture: { flag: false, note: "Smooth liquid" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Serve cool or warm" },
      osmolality: { flag: false, note: "Normal osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: null,
  },
  {
    name: "Yogurt (plain)",
    aliases: ["yogurt", "plain yogurt", "greek yogurt", "natural yogurt"],
    category: "Dairy & Alternatives",
    verdict: "SAFE",
    criteria: {
      acidity: { flag: false, note: "pH ~4.4-4.8, mildly acidic but well-tolerated due to coating properties" },
      texture: { flag: false, note: "Smooth and creamy" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Served cool" },
      osmolality: { flag: false, note: "Normal osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: null,
  },
  {
    name: "Yogurt (flavored)",
    aliases: ["flavored yogurt", "fruit yogurt", "strawberry yogurt", "blueberry yogurt"],
    category: "Dairy & Alternatives",
    verdict: "CAUTION",
    criteria: {
      acidity: { flag: true, note: "pH ~3.8-4.4, added fruit increases acidity" },
      texture: { flag: false, note: "Smooth if no fruit chunks" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Served cool" },
      osmolality: { flag: true, note: "Added sugars increase osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Use plain yogurt instead and add banana puree or a small amount of honey for flavor.",
  },
  {
    name: "Cream cheese",
    aliases: ["cream cheese", "soft cheese", "cheese", "cheese spread"],
    category: "Dairy & Alternatives",
    verdict: "SAFE",
    criteria: {
      acidity: { flag: false, note: "pH ~4.4-4.9, mildly acidic but well-tolerated" },
      texture: { flag: false, note: "Very smooth and creamy" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Served cool or room temperature" },
      osmolality: { flag: false, note: "Normal osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: null,
  },
  {
    name: "Cottage cheese",
    aliases: ["cottage cheese"],
    category: "Dairy & Alternatives",
    verdict: "CAUTION",
    criteria: {
      acidity: { flag: false, note: "pH ~4.7-5.0, mildly acidic" },
      texture: { flag: true, note: "Lumpy curds can irritate; must be pureed smooth" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Served cool" },
      osmolality: { flag: false, note: "Normal osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Blend in a food processor until completely smooth. Or substitute with cream cheese or plain yogurt.",
  },
  {
    name: "Ice cream",
    aliases: ["ice cream", "icecream", "vanilla ice cream"],
    category: "Dairy & Alternatives",
    verdict: "CAUTION",
    criteria: {
      acidity: { flag: false, note: "pH ~6.0-6.5, neutral" },
      texture: { flag: false, note: "Smooth when melted slightly" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: true, note: "Very cold temperature may cause discomfort" },
      osmolality: { flag: true, note: "High sugar content increases osmolality" },
      alcohol: { flag: false, note: "No alcohol unless rum raisin or similar" },
    },
    suggestion:
      "Let soften to a slightly melted consistency. Choose plain vanilla. Avoid flavors with chunks, nuts, or alcohol.",
  },
  {
    name: "Butter",
    aliases: ["butter", "unsalted butter", "salted butter"],
    category: "Dairy & Alternatives",
    verdict: "SAFE",
    criteria: {
      acidity: { flag: false, note: "pH ~6.1-6.4, neutral" },
      texture: { flag: false, note: "Smooth when melted or softened" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Use melted or softened" },
      osmolality: { flag: false, note: "Low osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: null,
  },
  {
    name: "Sour cream",
    aliases: ["sour cream"],
    category: "Dairy & Alternatives",
    verdict: "SAFE",
    criteria: {
      acidity: { flag: false, note: "pH ~4.4-4.6, mildly acidic but well-tolerated" },
      texture: { flag: false, note: "Smooth and creamy" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Served cool" },
      osmolality: { flag: false, note: "Normal osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: null,
  },
  {
    name: "Almond milk",
    aliases: ["almond milk"],
    category: "Dairy & Alternatives",
    verdict: "SAFE",
    criteria: {
      acidity: { flag: false, note: "pH ~6.5-8.0, neutral to alkaline" },
      texture: { flag: false, note: "Smooth liquid" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Served cool or warm" },
      osmolality: { flag: false, note: "Low osmolality (unsweetened)" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: null,
  },
  {
    name: "Oat milk",
    aliases: ["oat milk"],
    category: "Dairy & Alternatives",
    verdict: "SAFE",
    criteria: {
      acidity: { flag: false, note: "pH ~6.7-7.0, neutral" },
      texture: { flag: false, note: "Smooth and creamy liquid" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Served cool or warm" },
      osmolality: { flag: false, note: "Low osmolality (unsweetened)" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: null,
  },
  {
    name: "Coconut milk",
    aliases: ["coconut milk", "coconut cream"],
    category: "Dairy & Alternatives",
    verdict: "SAFE",
    criteria: {
      acidity: { flag: false, note: "pH ~6.1-7.0, neutral" },
      texture: { flag: false, note: "Smooth and creamy" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Served cool or warm" },
      osmolality: { flag: false, note: "Normal osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: null,
  },

  // =========================================================================
  // GRAINS & STARCHES
  // =========================================================================
  {
    name: "Oatmeal",
    aliases: ["oatmeal", "oats", "porridge", "oat porridge"],
    category: "Grains & Starches",
    verdict: "SAFE",
    criteria: {
      acidity: { flag: false, note: "pH ~6.2-6.8, neutral" },
      texture: { flag: false, note: "Smooth when cooked until soft and pureed" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Serve warm, not hot" },
      osmolality: { flag: false, note: "Low osmolality (without excessive sugar)" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: null,
  },
  {
    name: "Cream of wheat",
    aliases: ["cream of wheat", "farina", "semolina porridge", "hot cereal"],
    category: "Grains & Starches",
    verdict: "SAFE",
    criteria: {
      acidity: { flag: false, note: "pH ~6.0-6.5, neutral" },
      texture: { flag: false, note: "Very smooth when properly prepared" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Serve warm, not hot" },
      osmolality: { flag: false, note: "Low osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: null,
  },
  {
    name: "Rice (pureed)",
    aliases: ["rice", "white rice", "rice puree", "congee", "rice porridge"],
    category: "Grains & Starches",
    verdict: "SAFE",
    criteria: {
      acidity: { flag: false, note: "pH ~6.0-6.7, neutral" },
      texture: { flag: false, note: "Smooth when overcooked into congee or pureed" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Serve warm, not hot" },
      osmolality: { flag: false, note: "Low osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: null,
  },
  {
    name: "Pasta (pureed)",
    aliases: ["pasta", "noodles", "macaroni", "spaghetti", "pasta puree"],
    category: "Grains & Starches",
    verdict: "CAUTION",
    criteria: {
      acidity: { flag: false, note: "pH ~5.1-6.5, neutral" },
      texture: { flag: true, note: "Must be overcooked and pureed to be smooth enough" },
      spice: { flag: false, note: "No irritants when plain" },
      temperature: { flag: false, note: "Serve warm, not hot" },
      osmolality: { flag: false, note: "Low osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Overcook pasta until very soft, then puree with cream sauce or broth. Substitute with cream of wheat or pureed rice.",
  },
  {
    name: "Bread",
    aliases: ["bread", "white bread", "toast", "sandwich bread"],
    category: "Grains & Starches",
    verdict: "AVOID",
    criteria: {
      acidity: { flag: false, note: "pH ~5.0-6.0, neutral" },
      texture: { flag: true, note: "Dry, crumbly texture that can scratch and stick to damaged tissue" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Room temperature" },
      osmolality: { flag: false, note: "Low osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Avoid bread in solid form. Substitute with cream of wheat, oatmeal, or mashed potatoes.",
  },
  {
    name: "Crackers",
    aliases: ["crackers", "saltines", "cracker"],
    category: "Grains & Starches",
    verdict: "AVOID",
    criteria: {
      acidity: { flag: false, note: "pH ~6.5-7.0, neutral" },
      texture: { flag: true, note: "Hard, sharp edges that scratch damaged throat tissue" },
      spice: { flag: false, note: "No irritants when plain" },
      temperature: { flag: false, note: "Room temperature" },
      osmolality: { flag: true, note: "Saltines have high salt content" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Avoid entirely. Substitute with cream of wheat, oatmeal, or smooth mashed potatoes.",
  },
  {
    name: "Pancake",
    aliases: ["pancake", "pancakes", "flapjack", "flapjacks"],
    category: "Grains & Starches",
    verdict: "CAUTION",
    criteria: {
      acidity: { flag: false, note: "pH ~5.5-6.5, neutral" },
      texture: { flag: true, note: "Spongy texture can be difficult; must be soaked until very soft" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Serve warm, not hot" },
      osmolality: { flag: false, note: "Moderate" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Soak in milk or syrup until completely soft and mashable. Better to substitute with cream of wheat or oatmeal.",
  },
  {
    name: "Grits",
    aliases: ["grits", "hominy grits"],
    category: "Grains & Starches",
    verdict: "SAFE",
    criteria: {
      acidity: { flag: false, note: "pH ~5.5-6.2, neutral" },
      texture: { flag: false, note: "Smooth when cooked with plenty of liquid and butter" },
      spice: { flag: false, note: "No irritants when plain" },
      temperature: { flag: false, note: "Serve warm, not hot" },
      osmolality: { flag: false, note: "Low osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: null,
  },
  {
    name: "Quinoa",
    aliases: ["quinoa", "quinoa puree"],
    category: "Grains & Starches",
    verdict: "AVOID",
    criteria: {
      acidity: { flag: false, note: "pH ~6.0-6.5, neutral" },
      texture: { flag: true, note: "Small granular seeds do not puree smooth; gritty texture" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Serve warm, not hot" },
      osmolality: { flag: false, note: "Low osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Substitute with cream of wheat, smooth oatmeal, or pureed rice for similar nutritional value.",
  },

  // =========================================================================
  // NUTS & SEEDS
  // =========================================================================
  {
    name: "Smooth peanut butter",
    aliases: ["peanut butter", "pb", "smooth peanut butter", "creamy peanut butter"],
    category: "Nuts & Seeds",
    verdict: "SAFE",
    criteria: {
      acidity: { flag: false, note: "pH ~6.3-6.8, neutral" },
      texture: { flag: false, note: "Smooth/creamy variety is safe; avoid crunchy" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Room temperature" },
      osmolality: { flag: false, note: "Moderate" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: null,
  },
  {
    name: "Smooth almond butter",
    aliases: ["almond butter", "smooth almond butter", "creamy almond butter"],
    category: "Nuts & Seeds",
    verdict: "SAFE",
    criteria: {
      acidity: { flag: false, note: "pH ~6.0-6.5, neutral" },
      texture: { flag: false, note: "Smooth variety is safe; avoid crunchy" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Room temperature" },
      osmolality: { flag: false, note: "Moderate" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: null,
  },
  {
    name: "Chia seeds",
    aliases: ["chia seeds", "chia", "chia seed"],
    category: "Nuts & Seeds",
    verdict: "AVOID",
    criteria: {
      acidity: { flag: false, note: "pH ~6.5-7.0, neutral" },
      texture: { flag: true, note: "Seeds remain gritty even when soaked; gel texture with small hard seeds" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Room temperature" },
      osmolality: { flag: false, note: "Low osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Avoid entirely. For omega-3s and fiber, use smooth flaxseed oil added to shakes or soups instead.",
  },
  {
    name: "Flax seeds",
    aliases: ["flax seeds", "flaxseed", "flax", "flax seed", "linseed"],
    category: "Nuts & Seeds",
    verdict: "AVOID",
    criteria: {
      acidity: { flag: false, note: "pH ~6.0-6.5, neutral" },
      texture: { flag: true, note: "Hard seed fragments remain even when ground" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Room temperature" },
      osmolality: { flag: false, note: "Low osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Substitute with smooth flaxseed oil for nutritional benefits without texture risk.",
  },
  {
    name: "Sesame seeds",
    aliases: ["sesame seeds", "sesame", "sesame seed", "tahini"],
    category: "Nuts & Seeds",
    verdict: "AVOID",
    criteria: {
      acidity: { flag: false, note: "pH ~5.5-6.0, neutral" },
      texture: { flag: true, note: "Small hard seeds; tahini (sesame paste) may be gritty" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Room temperature" },
      osmolality: { flag: false, note: "Low osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Avoid whole seeds. Smooth tahini may be tolerable in small amounts mixed into other foods. Test carefully.",
  },
  {
    name: "Walnuts",
    aliases: ["walnuts", "walnut"],
    category: "Nuts & Seeds",
    verdict: "AVOID",
    criteria: {
      acidity: { flag: false, note: "pH ~5.4-5.7, neutral" },
      texture: { flag: true, note: "Hard, sharp fragments even when chopped fine" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Room temperature" },
      osmolality: { flag: false, note: "Low osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Substitute with smooth nut butters blended into shakes or smoothies.",
  },
  {
    name: "Almonds",
    aliases: ["almonds", "almond"],
    category: "Nuts & Seeds",
    verdict: "AVOID",
    criteria: {
      acidity: { flag: false, note: "pH ~6.0-6.5, neutral" },
      texture: { flag: true, note: "Hard and sharp even when sliced" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Room temperature" },
      osmolality: { flag: false, note: "Low osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Substitute with smooth almond butter in shakes or mixed into oatmeal.",
  },
  {
    name: "Cashews",
    aliases: ["cashews", "cashew"],
    category: "Nuts & Seeds",
    verdict: "AVOID",
    criteria: {
      acidity: { flag: false, note: "pH ~5.7-6.2, neutral" },
      texture: { flag: true, note: "Hard pieces even when chopped" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Room temperature" },
      osmolality: { flag: false, note: "Low osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Substitute with smooth cashew butter blended into shakes.",
  },
  {
    name: "Sunflower seeds",
    aliases: ["sunflower seeds", "sunflower seed"],
    category: "Nuts & Seeds",
    verdict: "AVOID",
    criteria: {
      acidity: { flag: false, note: "pH ~5.5-6.0, neutral" },
      texture: { flag: true, note: "Hard seed fragments" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Room temperature" },
      osmolality: { flag: false, note: "Low osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Substitute with sunflower seed butter (smooth) mixed into shakes or oatmeal.",
  },

  // =========================================================================
  // COMMERCIAL PRODUCTS
  // =========================================================================
  {
    name: "Ensure",
    aliases: ["ensure", "ensure shake", "ensure plus"],
    category: "Commercial Products",
    verdict: "SAFE",
    criteria: {
      acidity: { flag: false, note: "pH ~6.4-6.8, formulated to be gentle" },
      texture: { flag: false, note: "Smooth liquid" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Serve cool or room temperature" },
      osmolality: { flag: false, note: "Formulated for appropriate osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: null,
  },
  {
    name: "Boost",
    aliases: ["boost", "boost shake", "boost plus"],
    category: "Commercial Products",
    verdict: "SAFE",
    criteria: {
      acidity: { flag: false, note: "pH ~6.4-6.8, formulated to be gentle" },
      texture: { flag: false, note: "Smooth liquid" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Serve cool or room temperature" },
      osmolality: { flag: false, note: "Formulated for appropriate osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: null,
  },
  {
    name: "Pedialyte",
    aliases: ["pedialyte", "pedialyte popsicle"],
    category: "Commercial Products",
    verdict: "SAFE",
    criteria: {
      acidity: { flag: false, note: "pH ~5.0-5.4, formulated for oral rehydration" },
      texture: { flag: false, note: "Smooth liquid" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Serve cool" },
      osmolality: { flag: false, note: "Specifically designed for optimal osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: null,
  },
  {
    name: "Gatorade",
    aliases: ["gatorade", "sports drink", "electrolyte drink"],
    category: "Commercial Products",
    verdict: "CAUTION",
    criteria: {
      acidity: { flag: true, note: "pH ~2.9-3.2, acidic due to citric acid" },
      texture: { flag: false, note: "Smooth liquid" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Served cool" },
      osmolality: { flag: true, note: "High sugar and electrolyte content" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Substitute with Pedialyte for electrolyte replacement — it's formulated to be gentler. Dilute if Gatorade is the only option.",
  },
  {
    name: "Applesauce",
    aliases: ["applesauce", "apple sauce"],
    category: "Commercial Products",
    verdict: "CAUTION",
    criteria: {
      acidity: { flag: true, note: "pH ~3.3-3.6, acidic" },
      texture: { flag: false, note: "Smooth" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Served cool or room temperature" },
      osmolality: { flag: false, note: "Moderate sugar" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Choose unsweetened varieties. Mix with plain yogurt to buffer acidity. Substitute with banana puree or pear puree for a less acidic option.",
  },
  {
    name: "Baby food",
    aliases: ["baby food", "gerber", "baby puree"],
    category: "Commercial Products",
    verdict: "SAFE",
    criteria: {
      acidity: { flag: false, note: "Varies by flavor — choose non-citrus, non-tomato varieties" },
      texture: { flag: false, note: "Specifically formulated to be smooth" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Served at room temperature" },
      osmolality: { flag: false, note: "Formulated for gentle digestion" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: null,
  },
  {
    name: "Bone broth",
    aliases: ["bone broth", "bone stock"],
    category: "Commercial Products",
    verdict: "SAFE",
    criteria: {
      acidity: { flag: false, note: "pH ~5.5-6.5, neutral" },
      texture: { flag: false, note: "Smooth liquid" },
      spice: { flag: false, note: "No irritants when plain" },
      temperature: { flag: true, note: "Typically served hot — cool to warm before serving" },
      osmolality: { flag: false, note: "Moderate sodium — choose low-sodium if possible" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Cool to warm (not hot) before serving. Choose low-sodium varieties. Excellent for nutrition and hydration.",
  },
  {
    name: "Chicken broth",
    aliases: ["chicken broth", "chicken stock", "broth"],
    category: "Commercial Products",
    verdict: "SAFE",
    criteria: {
      acidity: { flag: false, note: "pH ~5.5-6.5, neutral" },
      texture: { flag: false, note: "Smooth liquid" },
      spice: { flag: false, note: "No irritants when plain" },
      temperature: { flag: true, note: "Typically served hot — cool to warm before serving" },
      osmolality: { flag: false, note: "Moderate sodium — choose low-sodium if possible" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Cool to warm (not hot) before serving. Choose low-sodium varieties.",
  },
  {
    name: "Cream soup (not tomato)",
    aliases: [
      "cream soup",
      "cream of mushroom",
      "cream of chicken",
      "cream of broccoli",
      "cream of celery",
      "cream of potato",
      "potato soup",
      "mushroom soup",
    ],
    category: "Commercial Products",
    verdict: "SAFE",
    criteria: {
      acidity: { flag: false, note: "pH ~5.5-6.5, neutral for non-tomato varieties" },
      texture: { flag: false, note: "Smooth when properly blended" },
      spice: { flag: false, note: "Mild; check label for pepper/spices" },
      temperature: { flag: true, note: "Typically served hot — cool to warm before serving" },
      osmolality: { flag: false, note: "Moderate sodium — choose low-sodium" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Cool to warm before serving. Choose low-sodium varieties. Blend until completely smooth.",
  },
  {
    name: "Tomato soup",
    aliases: ["tomato soup", "tomato bisque"],
    category: "Commercial Products",
    verdict: "AVOID",
    criteria: {
      acidity: { flag: true, note: "pH ~4.0-4.6, acidic from tomatoes" },
      texture: { flag: false, note: "Smooth" },
      spice: { flag: false, note: "Mild usually" },
      temperature: { flag: true, note: "Served hot — would need cooling" },
      osmolality: { flag: false, note: "Moderate" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Substitute with cream of mushroom, cream of chicken, or butternut squash soup.",
  },
  {
    name: "Protein powder",
    aliases: ["protein powder", "whey protein", "protein shake", "protein supplement"],
    category: "Commercial Products",
    verdict: "SAFE",
    criteria: {
      acidity: { flag: false, note: "pH varies; choose unflavored or vanilla" },
      texture: { flag: false, note: "Smooth when properly mixed" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Served cool" },
      osmolality: { flag: false, note: "Moderate when properly diluted" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: null,
  },

  // =========================================================================
  // CONDIMENTS & ADDITIVES
  // =========================================================================
  {
    name: "Honey",
    aliases: ["honey", "raw honey"],
    category: "Condiments & Additives",
    verdict: "CAUTION",
    criteria: {
      acidity: { flag: true, note: "pH ~3.4-6.1, can be acidic" },
      texture: { flag: false, note: "Smooth liquid" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Room temperature" },
      osmolality: { flag: true, note: "Very high sugar concentration" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Use in small amounts only, diluted in warm water or mixed into yogurt. Do not use large quantities.",
  },
  {
    name: "Maple syrup",
    aliases: ["maple syrup", "syrup"],
    category: "Condiments & Additives",
    verdict: "CAUTION",
    criteria: {
      acidity: { flag: false, note: "pH ~5.1-7.0, mostly neutral" },
      texture: { flag: false, note: "Smooth liquid" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Room temperature" },
      osmolality: { flag: true, note: "Very high sugar concentration" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Use in small amounts only. Dilute into oatmeal or cream of wheat rather than using directly.",
  },
  {
    name: "Sugar",
    aliases: ["sugar", "white sugar", "granulated sugar", "brown sugar"],
    category: "Condiments & Additives",
    verdict: "CAUTION",
    criteria: {
      acidity: { flag: false, note: "pH neutral" },
      texture: { flag: false, note: "Dissolves completely" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "N/A" },
      osmolality: { flag: true, note: "High osmolality when concentrated" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Use sparingly. High sugar concentration pulls moisture from damaged cells. Small amounts dissolved in foods are fine.",
  },
  {
    name: "Salt",
    aliases: ["salt", "table salt", "sea salt", "sodium"],
    category: "Condiments & Additives",
    verdict: "CAUTION",
    criteria: {
      acidity: { flag: false, note: "pH neutral" },
      texture: { flag: false, note: "Dissolves completely" },
      spice: { flag: false, note: "No irritants in small amounts" },
      temperature: { flag: false, note: "N/A" },
      osmolality: { flag: true, note: "High osmolality; salt on damaged tissue causes burning pain" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Use very sparingly. Season food lightly. Choose low-sodium versions of commercial products.",
  },
  {
    name: "Olive oil",
    aliases: ["olive oil", "evoo", "extra virgin olive oil"],
    category: "Condiments & Additives",
    verdict: "SAFE",
    criteria: {
      acidity: { flag: false, note: "pH neutral" },
      texture: { flag: false, note: "Smooth liquid" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Room temperature" },
      osmolality: { flag: false, note: "N/A" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: null,
  },
  {
    name: "Coconut oil",
    aliases: ["coconut oil"],
    category: "Condiments & Additives",
    verdict: "SAFE",
    criteria: {
      acidity: { flag: false, note: "pH neutral" },
      texture: { flag: false, note: "Smooth when melted" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Melts at warm temperature" },
      osmolality: { flag: false, note: "N/A" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: null,
  },
  {
    name: "Vanilla extract",
    aliases: ["vanilla extract", "vanilla", "pure vanilla", "vanilla flavoring"],
    category: "Condiments & Additives",
    verdict: "AVOID",
    criteria: {
      acidity: { flag: false, note: "pH neutral" },
      texture: { flag: false, note: "Smooth liquid" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Room temperature" },
      osmolality: { flag: false, note: "Low osmolality" },
      alcohol: { flag: true, note: "Contains 35% alcohol by volume" },
    },
    suggestion:
      "Substitute with vanilla bean paste (alcohol-free) or vanilla powder. Check label for alcohol-free alternatives.",
  },
  {
    name: "Soy sauce",
    aliases: ["soy sauce", "shoyu", "tamari"],
    category: "Condiments & Additives",
    verdict: "AVOID",
    criteria: {
      acidity: { flag: true, note: "pH ~4.4-5.4, acidic" },
      texture: { flag: false, note: "Smooth liquid" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Room temperature" },
      osmolality: { flag: true, note: "Extremely high sodium — causes severe pain on damaged tissue" },
      alcohol: { flag: false, note: "May contain trace alcohol from fermentation" },
    },
    suggestion:
      "Avoid entirely. Use a small amount of butter or a mild herb for flavoring instead.",
  },
  {
    name: "Ketchup",
    aliases: ["ketchup", "catsup"],
    category: "Condiments & Additives",
    verdict: "AVOID",
    criteria: {
      acidity: { flag: true, note: "pH ~3.7-3.9, acidic from tomatoes and vinegar" },
      texture: { flag: false, note: "Smooth" },
      spice: { flag: false, note: "Mild" },
      temperature: { flag: false, note: "Room temperature" },
      osmolality: { flag: true, note: "High sugar and salt content" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Avoid entirely. No good substitute — use butter or cream sauce for moisture/flavor.",
  },
  {
    name: "Mustard",
    aliases: ["mustard", "yellow mustard", "dijon mustard", "dijon"],
    category: "Condiments & Additives",
    verdict: "AVOID",
    criteria: {
      acidity: { flag: true, note: "pH ~3.6, acidic from vinegar" },
      texture: { flag: false, note: "Smooth" },
      spice: { flag: true, note: "Contains mustard seed compounds that irritate mucosa" },
      temperature: { flag: false, note: "Room temperature" },
      osmolality: { flag: false, note: "Moderate" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: "Avoid entirely. Use butter or cream cheese for sandwich/food moisture.",
  },
  {
    name: "Mayonnaise",
    aliases: ["mayonnaise", "mayo"],
    category: "Condiments & Additives",
    verdict: "CAUTION",
    criteria: {
      acidity: { flag: true, note: "pH ~3.8-4.0, acidic from vinegar/lemon juice" },
      texture: { flag: false, note: "Smooth and creamy" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Served cool" },
      osmolality: { flag: false, note: "Moderate" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Use sparingly. The fat content can help coat the throat. Substitute with sour cream or cream cheese for a less acidic option.",
  },
  {
    name: "Hot sauce",
    aliases: ["hot sauce", "tabasco", "sriracha", "chili sauce", "hot pepper sauce"],
    category: "Condiments & Additives",
    verdict: "AVOID",
    criteria: {
      acidity: { flag: true, note: "pH ~3.3-3.7, acidic from vinegar" },
      texture: { flag: false, note: "Smooth liquid" },
      spice: { flag: true, note: "High capsaicin — causes severe burning on damaged tissue" },
      temperature: { flag: false, note: "Room temperature" },
      osmolality: { flag: false, note: "High sodium" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: "Avoid entirely. No substitute — spicy food must be eliminated.",
  },
  {
    name: "Vinegar",
    aliases: ["vinegar", "apple cider vinegar", "white vinegar", "balsamic vinegar", "acv"],
    category: "Condiments & Additives",
    verdict: "AVOID",
    criteria: {
      acidity: { flag: true, note: "pH ~2.4-3.4, extremely acidic" },
      texture: { flag: false, note: "Smooth liquid" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Room temperature" },
      osmolality: { flag: false, note: "Low osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: "Avoid entirely. Use butter, cream, or mild herbs for flavor.",
  },
  {
    name: "Citric acid",
    aliases: ["citric acid"],
    category: "Condiments & Additives",
    verdict: "AVOID",
    criteria: {
      acidity: { flag: true, note: "Extremely acidic food additive" },
      texture: { flag: false, note: "Dissolves" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "N/A" },
      osmolality: { flag: false, note: "N/A" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Check ingredient labels — citric acid is hidden in many processed foods. Avoid any product listing it.",
  },
  {
    name: "Black pepper",
    aliases: ["black pepper", "pepper", "ground pepper", "cracked pepper"],
    category: "Condiments & Additives",
    verdict: "AVOID",
    criteria: {
      acidity: { flag: false, note: "pH neutral" },
      texture: { flag: true, note: "Coarse particles irritate damaged tissue" },
      spice: { flag: true, note: "Piperine compound causes burning sensation on damaged mucosa" },
      temperature: { flag: false, note: "N/A" },
      osmolality: { flag: false, note: "N/A" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Avoid entirely. Use mild herbs like basil, parsley, or very small amounts of cinnamon for flavor.",
  },
  {
    name: "Cinnamon",
    aliases: ["cinnamon", "cinnamon powder", "ground cinnamon"],
    category: "Condiments & Additives",
    verdict: "SAFE",
    criteria: {
      acidity: { flag: false, note: "pH neutral" },
      texture: { flag: false, note: "Fine powder that dissolves well" },
      spice: { flag: false, note: "Very mild; not an irritant in small amounts" },
      temperature: { flag: false, note: "N/A" },
      osmolality: { flag: false, note: "N/A" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: null,
  },
  {
    name: "Nutmeg",
    aliases: ["nutmeg", "ground nutmeg"],
    category: "Condiments & Additives",
    verdict: "SAFE",
    criteria: {
      acidity: { flag: false, note: "pH neutral" },
      texture: { flag: false, note: "Fine powder" },
      spice: { flag: false, note: "Mild in small amounts" },
      temperature: { flag: false, note: "N/A" },
      osmolality: { flag: false, note: "N/A" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: null,
  },
  {
    name: "Ginger",
    aliases: ["ginger", "raw ginger", "ginger root", "ginger powder", "fresh ginger"],
    category: "Condiments & Additives",
    verdict: "AVOID",
    criteria: {
      acidity: { flag: false, note: "pH ~5.6-5.9, neutral" },
      texture: { flag: false, note: "Fibrous raw; powder is fine" },
      spice: { flag: true, note: "Contains gingerol — causes burning on damaged throat tissue" },
      temperature: { flag: false, note: "Varies" },
      osmolality: { flag: false, note: "Low osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Avoid raw ginger and strong ginger flavoring. Very small amounts of ginger powder in baked goods may be tolerable. Use cinnamon instead for warming flavor.",
  },

  // =========================================================================
  // BEVERAGES
  // =========================================================================
  {
    name: "Water",
    aliases: ["water", "still water", "filtered water", "tap water"],
    category: "Beverages",
    verdict: "SAFE",
    criteria: {
      acidity: { flag: false, note: "pH ~7.0, neutral" },
      texture: { flag: false, note: "Smooth liquid" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Serve room temperature or slightly cool" },
      osmolality: { flag: false, note: "Optimal osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: null,
  },
  {
    name: "Apple juice",
    aliases: ["apple juice", "apple cider"],
    category: "Beverages",
    verdict: "CAUTION",
    criteria: {
      acidity: { flag: true, note: "pH ~3.4-4.0, acidic" },
      texture: { flag: false, note: "Smooth liquid" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Served cool" },
      osmolality: { flag: true, note: "High sugar concentration" },
      alcohol: { flag: false, note: "No alcohol (unless hard cider)" },
    },
    suggestion:
      "Dilute 50/50 with water to reduce acidity and sugar concentration. Substitute with pear nectar or watermelon juice.",
  },
  {
    name: "Orange juice",
    aliases: ["orange juice", "oj", "fresh squeezed orange juice"],
    category: "Beverages",
    verdict: "AVOID",
    criteria: {
      acidity: { flag: true, note: "pH ~3.3-4.2, highly acidic citrus" },
      texture: { flag: false, note: "Smooth liquid (if no pulp)" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Served cool" },
      osmolality: { flag: true, note: "High sugar concentration" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Avoid entirely. Substitute with diluted pear juice, watermelon juice, or Pedialyte for hydration.",
  },
  {
    name: "Cranberry juice",
    aliases: ["cranberry juice", "cran juice"],
    category: "Beverages",
    verdict: "AVOID",
    criteria: {
      acidity: { flag: true, note: "pH ~2.3-2.5, extremely acidic" },
      texture: { flag: false, note: "Smooth liquid" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Served cool" },
      osmolality: { flag: true, note: "Usually heavily sweetened" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Avoid entirely. Substitute with diluted pear juice or Pedialyte.",
  },
  {
    name: "Grape juice",
    aliases: ["grape juice"],
    category: "Beverages",
    verdict: "AVOID",
    criteria: {
      acidity: { flag: true, note: "pH ~3.0-4.0, acidic" },
      texture: { flag: false, note: "Smooth liquid" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Served cool" },
      osmolality: { flag: true, note: "Very high sugar concentration" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Avoid entirely. Substitute with diluted pear juice or watermelon juice.",
  },
  {
    name: "Coffee",
    aliases: ["coffee", "espresso", "latte", "cappuccino"],
    category: "Beverages",
    verdict: "AVOID",
    criteria: {
      acidity: { flag: true, note: "pH ~4.8-5.1, moderately acidic" },
      texture: { flag: false, note: "Smooth liquid" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: true, note: "Typically served very hot" },
      osmolality: { flag: false, note: "Low osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Avoid due to acidity and typical serving temperature. If needed, use cold brew (lower acid) diluted with milk, served cool.",
  },
  {
    name: "Tea",
    aliases: ["tea", "black tea", "green tea", "herbal tea", "chamomile tea"],
    category: "Beverages",
    verdict: "CAUTION",
    criteria: {
      acidity: { flag: false, note: "pH ~5.5-7.0 for most teas; herbal teas are milder" },
      texture: { flag: false, note: "Smooth liquid" },
      spice: { flag: false, note: "No irritants (plain tea)" },
      temperature: { flag: true, note: "Typically served hot — must cool before drinking" },
      osmolality: { flag: false, note: "Low osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Cool to warm or room temperature before drinking. Choose mild herbal teas like chamomile. Avoid lemon in tea.",
  },
  {
    name: "Soda",
    aliases: ["soda", "cola", "coke", "pepsi", "soft drink", "pop"],
    category: "Beverages",
    verdict: "AVOID",
    criteria: {
      acidity: { flag: true, note: "pH ~2.5-3.5, highly acidic from phosphoric/citric acid" },
      texture: { flag: false, note: "Liquid" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Served cool" },
      osmolality: { flag: true, note: "Very high sugar content" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Avoid entirely. Carbonation also irritates damaged tissue. Substitute with water, Pedialyte, or milk.",
  },
  {
    name: "Sparkling water",
    aliases: ["sparkling water", "seltzer", "carbonated water", "club soda", "la croix"],
    category: "Beverages",
    verdict: "CAUTION",
    criteria: {
      acidity: { flag: true, note: "pH ~3.0-4.5, carbonic acid from carbonation" },
      texture: { flag: false, note: "Liquid" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Served cool" },
      osmolality: { flag: false, note: "Low osmolality" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Let go flat before drinking, or substitute with plain still water.",
  },
  {
    name: "Banana smoothie",
    aliases: ["banana smoothie", "banana shake", "smoothie banana"],
    category: "Beverages",
    verdict: "SAFE",
    criteria: {
      acidity: { flag: false, note: "pH ~5.0-5.5, low acidity" },
      texture: { flag: false, note: "Smooth when well blended" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Served cool" },
      osmolality: { flag: false, note: "Moderate" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion: null,
  },
  {
    name: "Berry smoothie",
    aliases: ["berry smoothie", "mixed berry smoothie", "smoothie berry"],
    category: "Beverages",
    verdict: "AVOID",
    criteria: {
      acidity: { flag: true, note: "pH ~3.5-4.0, acidic from berries" },
      texture: { flag: true, note: "Berry seeds remain even when blended" },
      spice: { flag: false, note: "No irritants" },
      temperature: { flag: false, note: "Served cool" },
      osmolality: { flag: false, note: "Moderate" },
      alcohol: { flag: false, note: "No alcohol" },
    },
    suggestion:
      "Substitute with banana-based smoothie using milk, banana, smooth peanut butter, and oats.",
  },
];

export default foodDatabase;
