"use client";

import { useEffect, useRef, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { databases, DATABASE_ID, COLLECTIONS } from "@/lib/appwrite";
import Link from "next/link";

export default function ViewBriefPage() {
  const params = useParams();
  const router = useRouter();
  const [brief, setBrief] = useState(null);
  const [loading, setLoading] = useState(true);
  const [pdfLoading, setPdfLoading] = useState(false);
  const briefContentRef = useRef(null);

  useEffect(() => {
    async function loadBrief() {
      try {
        const doc = await databases.getDocument(
          DATABASE_ID,
          COLLECTIONS.APPOINTMENT_BRIEFS,
          params.id
        );
        setBrief(doc);
      } catch (error) {
        console.error("Error loading brief:", error);
      }
      setLoading(false);
    }
    loadBrief();
  }, [params.id]);

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadPdf = async () => {
    if (!briefContentRef.current || pdfLoading) return;
    setPdfLoading(true);

    try {
      const html2pdf = (await import("html2pdf.js")).default;

      // Build a self-contained element for PDF rendering so we don't
      // alter the on-screen DOM or rely on Tailwind classes (which
      // html2pdf cannot resolve from the stylesheet).
      const wrapper = document.createElement("div");
      wrapper.style.cssText =
        "font-family: system-ui, -apple-system, sans-serif; color: #111; padding: 0;";

      // Header
      const header = document.createElement("div");
      header.style.cssText =
        "border-bottom: 2px solid #2563eb; padding-bottom: 12px; margin-bottom: 24px;";
      header.innerHTML =
        `<div style="font-size: 20px; font-weight: 700; color: #2563eb;">RegimenIQ &mdash; Appointment Brief</div>` +
        `<div style="font-size: 14px; color: #555; margin-top: 4px;">${brief.patientName || "Patient"} &middot; ${new Date(brief.createdAt).toLocaleDateString()}</div>`;
      wrapper.appendChild(header);

      // Clone the rendered brief content
      const content = briefContentRef.current.cloneNode(true);
      // Inline basic styles so the PDF renders correctly without Tailwind
      content.querySelectorAll("h1").forEach((el) => {
        el.style.cssText =
          "font-size: 24px; font-weight: 700; color: #111; margin-bottom: 12px;";
      });
      content.querySelectorAll("h2").forEach((el) => {
        el.style.cssText =
          "font-size: 20px; font-weight: 600; color: #111; margin-top: 20px; margin-bottom: 10px;";
      });
      content.querySelectorAll("h3").forEach((el) => {
        el.style.cssText =
          "font-size: 17px; font-weight: 500; color: #111; margin-top: 16px; margin-bottom: 8px;";
      });
      content.querySelectorAll("p").forEach((el) => {
        el.style.cssText =
          "font-size: 13px; color: #374151; margin-bottom: 6px; line-height: 1.6;";
      });
      content.querySelectorAll("li").forEach((el) => {
        el.style.cssText =
          "font-size: 13px; color: #374151; margin-left: 24px; margin-bottom: 4px; line-height: 1.6;";
      });
      content.querySelectorAll("hr").forEach((el) => {
        el.style.cssText =
          "border: none; border-top: 1px solid #d1d5db; margin: 20px 0;";
      });
      content.querySelectorAll("strong").forEach((el) => {
        el.style.fontWeight = "600";
      });
      wrapper.appendChild(content);

      // Footer / disclaimer
      const footer = document.createElement("div");
      footer.style.cssText =
        "border-top: 1px solid #d1d5db; padding-top: 12px; margin-top: 32px; text-align: center; font-size: 11px; color: #6b7280;";
      footer.textContent =
        "Generated by RegimenIQ \u00B7 Not a substitute for professional medical advice";
      wrapper.appendChild(footer);

      const patientSlug = (brief.patientName || "Patient")
        .replace(/[^a-zA-Z0-9]+/g, "_")
        .replace(/^_|_$/g, "");
      const titleSlug = (brief.title || "Brief")
        .replace(/[^a-zA-Z0-9]+/g, "_")
        .replace(/^_|_$/g, "");
      const dateStr = new Date(brief.createdAt)
        .toISOString()
        .slice(0, 10)
        .replace(/-/g, "");
      const filename = `${patientSlug}_${titleSlug}_${dateStr}.pdf`;

      await html2pdf()
        .set({
          margin: [10, 12, 10, 12],
          filename,
          image: { type: "jpeg", quality: 0.98 },
          html2canvas: { scale: 2, useCORS: true },
          jsPDF: { unit: "mm", format: "letter", orientation: "portrait" },
        })
        .from(wrapper)
        .save();
    } catch (error) {
      console.error("Error generating PDF:", error);
    } finally {
      setPdfLoading(false);
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center py-12">
        <div className="h-8 w-8 animate-spin rounded-full border-b-2 border-t-2 border-blue-600"></div>
      </div>
    );
  }

  if (!brief) {
    return (
      <div className="text-center">
        <h1 className="text-2xl font-bold text-gray-900">Brief not found</h1>
        <Link
          href="/dashboard/appointments"
          className="mt-4 inline-block text-blue-600 hover:text-blue-500"
        >
          ← Back to Appointments
        </Link>
      </div>
    );
  }

  return (
    <>
      {/* No-print header */}
      <div className="mb-6 print:hidden">
        <Link
          href="/dashboard/appointments"
          className="text-sm text-blue-600 hover:text-blue-500"
        >
          ← Back to Appointments
        </Link>
      </div>

      <div className="mb-6 flex flex-col gap-3 print:hidden sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="text-xl font-bold text-gray-900 sm:text-2xl">{brief.title}</h1>
          <p className="mt-1 text-sm text-gray-600">
            Created {new Date(brief.createdAt).toLocaleDateString()}
          </p>
        </div>
        <div className="flex gap-2">
          <button
            onClick={handleDownloadPdf}
            disabled={pdfLoading}
            className="inline-flex items-center gap-2 rounded-md bg-blue-600 px-4 py-2.5 text-sm font-medium text-white hover:bg-blue-700 disabled:opacity-50"
          >
            {pdfLoading ? (
              <>
                <span className="inline-block h-4 w-4 animate-spin rounded-full border-2 border-white border-t-transparent"></span>
                Generating...
              </>
            ) : (
              "Download PDF"
            )}
          </button>
          <button
            onClick={handlePrint}
            className="rounded-md border border-gray-300 px-4 py-2.5 text-sm font-medium text-gray-700 hover:bg-gray-50"
          >
            Print
          </button>
        </div>
      </div>

      {/* Brief Content - Print-friendly */}
      <div className="rounded-lg border border-gray-200 bg-white p-4 shadow-sm sm:p-8 print:border-0 print:shadow-none">
        <div ref={briefContentRef} className="prose max-w-none">
          {brief.generatedContent.split("\n").map((line, idx) => {
            // Parse markdown-style content
            if (line.startsWith("# ")) {
              return (
                <h1 key={idx} className="mb-4 text-3xl font-bold text-gray-900">
                  {line.substring(2)}
                </h1>
              );
            }
            if (line.startsWith("## ")) {
              return (
                <h2 key={idx} className="mb-3 mt-6 text-2xl font-semibold text-gray-900">
                  {line.substring(3)}
                </h2>
              );
            }
            if (line.startsWith("### ")) {
              return (
                <h3 key={idx} className="mb-2 mt-4 text-xl font-medium text-gray-900">
                  {line.substring(4)}
                </h3>
              );
            }
            if (line.startsWith("**") && line.endsWith("**")) {
              return (
                <p key={idx} className="mb-2 font-semibold text-gray-900">
                  {line.replaceAll("**", "")}
                </p>
              );
            }
            if (line.includes("**")) {
              const parts = line.split("**");
              return (
                <p key={idx} className="mb-2 text-gray-700">
                  {parts.map((part, i) =>
                    i % 2 === 0 ? (
                      part
                    ) : (
                      <strong key={i} className="font-semibold">
                        {part}
                      </strong>
                    )
                  )}
                </p>
              );
            }
            if (line.startsWith("- ")) {
              return (
                <li key={idx} className="ml-6 text-gray-700">
                  {line.substring(2)}
                </li>
              );
            }
            if (line === "---") {
              return <hr key={idx} className="my-6 border-gray-300" />;
            }
            if (line.startsWith("*") && line.endsWith("*")) {
              return (
                <p key={idx} className="italic text-gray-600">
                  {line.substring(1, line.length - 1)}
                </p>
              );
            }
            if (line.trim() === "") {
              return <br key={idx} />;
            }
            return (
              <p key={idx} className="mb-2 text-gray-700">
                {line}
              </p>
            );
          })}
        </div>
      </div>

      {/* Print-only footer */}
      <div className="hidden print:block print:mt-8">
        <p className="text-center text-xs text-gray-500">
          Generated by RegimenIQ · Not a substitute for professional medical
          advice
        </p>
      </div>
    </>
  );
}
