"use client";

import { useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { getCurrentUser } from "@/lib/auth";
import {
  getPatient,
  getRegimenItems,
  getResearchNotes,
  createAppointmentBrief,
} from "@/lib/data";
import { checkInteractions } from "@/lib/interactions";
import Link from "next/link";

export default function NewAppointmentBriefPage() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const patientId = searchParams.get("patient");

  const [patient, setPatient] = useState(null);
  const [regimenItems, setRegimenItems] = useState([]);
  const [interactions, setInteractions] = useState([]);
  const [researchNotes, setResearchNotes] = useState([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);

  const [formData, setFormData] = useState({
    title: "",
    appointmentDate: "",
    doctorName: "",
    appointmentType: "Follow-up",
    customNotes: "",
  });

  useEffect(() => {
    async function loadData() {
      if (!patientId) {
        router.push("/dashboard/appointments");
        return;
      }

      const user = await getCurrentUser();
      if (!user) {
        router.push("/login");
        return;
      }

      const patientResult = await getPatient(patientId);
      if (patientResult.success) {
        setPatient(patientResult.data);

        // Set default title
        setFormData((prev) => ({
          ...prev,
          title: `Appointment Brief - ${patientResult.data.name}`,
        }));

        // Load regimen
        const regimenResult = await getRegimenItems(user.$id, patientId, true);
        if (regimenResult.success) {
          setRegimenItems(regimenResult.data);
        }

        // Check interactions
        const interactionResult = await checkInteractions(user.$id, patientId);
        if (interactionResult.success) {
          setInteractions(interactionResult.data);
        }

        // Load research notes
        const researchResult = await getResearchNotes(user.$id, patientId);
        if (researchResult.success) {
          setResearchNotes(researchResult.data);
        }
      }

      setLoading(false);
    }
    loadData();
  }, [patientId, router]);

  const generateBriefContent = () => {
    let content = `# Appointment Brief: ${patient.name}\n\n`;
    
    if (formData.doctorName) {
      content += `**Doctor:** ${formData.doctorName}\n`;
    }
    if (formData.appointmentType) {
      content += `**Type:** ${formData.appointmentType}\n`;
    }
    if (formData.appointmentDate) {
      content += `**Date:** ${new Date(formData.appointmentDate).toLocaleDateString("en-US", { weekday: "long", year: "numeric", month: "long", day: "numeric" })}\n`;
    }

    content += `\n**Generated:** ${new Date().toLocaleDateString()}\n\n`;
    content += `---\n\n`;

    // Diagnosis
    if (patient.diagnosis) {
      content += `## Diagnosis\n\n${patient.diagnosis}\n\n`;
    }

    // Current Regimen
    content += `## Current Treatment Regimen\n\n`;
    if (regimenItems.length > 0) {
      regimenItems.forEach((item) => {
        content += `### ${item.name}\n`;
        content += `- **Type:** ${item.category}\n`;
        if (item.dosage) content += `- **Dosage:** ${item.dosage}\n`;
        if (item.frequency) content += `- **Frequency:** ${item.frequency}\n`;
        if (item.source) content += `- **Prescribed by:** ${item.source}\n`;
        if (item.startDate) content += `- **Start Date:** ${new Date(item.startDate).toLocaleDateString()}\n`;
        if (item.notes) content += `- **Notes:** ${item.notes}\n`;
        content += `\n`;
      });
    } else {
      content += `No active regimen items.\n\n`;
    }

    // Potential Interactions
    if (interactions.length > 0) {
      content += `## ⚠️ Potential Interactions to Discuss\n\n`;
      interactions.forEach((interaction, idx) => {
        content += `### ${idx + 1}. ${interaction.items?.map((i) => i.name).join(" + ") || "Interaction"}\n`;
        content += `- **Severity:** ${interaction.severity}\n`;
        content += `- **Description:** ${interaction.description}\n`;
        if (interaction.sources && interaction.sources.length > 0) {
          content += `- **Sources:** ${interaction.sources.map((s) => s.title || s.url).join(", ")}\n`;
        }
        content += `\n`;
      });
    }

    // Research Questions
    if (researchNotes.length > 0) {
      content += `## Research Topics & Questions\n\n`;
      researchNotes.slice(0, 5).forEach((note, idx) => {
        content += `### ${idx + 1}. ${note.topic}\n`;
        content += `${note.content.substring(0, 200)}${note.content.length > 200 ? "..." : ""}\n\n`;
      });
    }

    // Custom Notes
    if (formData.customNotes) {
      content += `## Additional Notes\n\n${formData.customNotes}\n\n`;
    }

    // Footer
    content += `---\n\n`;
    content += `*This brief was generated by RegimenIQ for informational purposes only. It does not constitute medical advice.*\n`;

    return content;
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setGenerating(true);

    const user = await getCurrentUser();
    const briefContent = generateBriefContent();

    const result = await createAppointmentBrief(user.$id, patientId, {
      title: formData.title,
      appointmentDate: formData.appointmentDate || null,
      doctorName: formData.doctorName,
      appointmentType: formData.appointmentType,
      generatedContent: briefContent,
      includedRegimen: regimenItems.map((i) => i.$id),
      includedInteractions: [], // Interactions are ephemeral
      includedResearch: researchNotes.slice(0, 5).map((n) => n.$id),
      customNotes: formData.customNotes,
    });

    if (result.success) {
      router.push(`/dashboard/appointments/${result.data.$id}`);
    }
    setGenerating(false);
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center py-12">
        <div className="h-8 w-8 animate-spin rounded-full border-b-2 border-t-2 border-blue-600"></div>
      </div>
    );
  }

  if (!patient) {
    return (
      <div className="text-center">
        <h1 className="text-2xl font-bold text-gray-900">Patient not found</h1>
        <Link
          href="/dashboard/appointments"
          className="mt-4 inline-block text-blue-600 hover:text-blue-500"
        >
          ← Back to Appointments
        </Link>
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-4xl">
      <div className="mb-6">
        <Link
          href="/dashboard/appointments"
          className="text-sm text-blue-600 hover:text-blue-500"
        >
          ← Back to Appointments
        </Link>
      </div>

      <div className="mb-8 rounded-lg border border-gray-200 bg-white p-6 shadow-sm">
        <h1 className="mb-2 text-2xl font-bold text-gray-900">
          Generate Appointment Brief
        </h1>
        <p className="text-sm text-gray-600">
          Creating brief for <strong>{patient.name}</strong>
        </p>
      </div>

      {/* Preview */}
      <div className="mb-8 rounded-lg border border-blue-200 bg-blue-50 p-6">
        <h2 className="mb-4 text-lg font-semibold text-blue-900">
          Brief Preview
        </h2>
        <div className="grid gap-4 text-sm text-blue-800 sm:grid-cols-3">
          <div>
            <p className="font-medium">Regimen Items</p>
            <p className="text-2xl font-bold">{regimenItems.length}</p>
          </div>
          <div>
            <p className="font-medium">Flagged Interactions</p>
            <p className="text-2xl font-bold text-yellow-700">
              {interactions.length}
            </p>
          </div>
          <div>
            <p className="font-medium">Research Notes</p>
            <p className="text-2xl font-bold">{researchNotes.length}</p>
          </div>
        </div>
      </div>

      {/* Form */}
      <div className="rounded-lg border border-gray-200 bg-white p-6 shadow-sm">
        <form onSubmit={handleSubmit} className="space-y-6">
          <div>
            <label className="block text-sm font-medium text-gray-700">
              Brief Title *
            </label>
            <input
              type="text"
              required
              value={formData.title}
              onChange={(e) =>
                setFormData((prev) => ({ ...prev, title: e.target.value }))
              }
              className="mt-1 w-full rounded-md border border-gray-300 px-3 py-2 focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500"
            />
          </div>

          <div className="grid gap-4 sm:grid-cols-2">
            <div>
              <label className="block text-sm font-medium text-gray-700">
                Doctor Name
              </label>
              <input
                type="text"
                value={formData.doctorName}
                onChange={(e) =>
                  setFormData((prev) => ({ ...prev, doctorName: e.target.value }))
                }
                className="mt-1 w-full rounded-md border border-gray-300 px-3 py-2 focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500"
                placeholder="e.g., Dr. Emily Chen"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700">
                Appointment Type
              </label>
              <select
                value={formData.appointmentType}
                onChange={(e) =>
                  setFormData((prev) => ({ ...prev, appointmentType: e.target.value }))
                }
                className="mt-1 w-full rounded-md border border-gray-300 px-3 py-2 focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500"
              >
                <option value="Follow-up">Follow-up</option>
                <option value="Initial consultation">Initial consultation</option>
                <option value="Treatment planning">Treatment planning</option>
                <option value="Results review">Results review</option>
                <option value="Other">Other</option>
              </select>
            </div>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700">
              Appointment Date
            </label>
            <input
              type="date"
              value={formData.appointmentDate}
              onChange={(e) =>
                setFormData((prev) => ({
                  ...prev,
                  appointmentDate: e.target.value,
                }))
              }
              className="mt-1 w-full rounded-md border border-gray-300 px-3 py-2 focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500 sm:w-auto"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700">
              Additional Notes
            </label>
            <textarea
              rows={6}
              value={formData.customNotes}
              onChange={(e) =>
                setFormData((prev) => ({ ...prev, customNotes: e.target.value }))
              }
              className="mt-1 w-full rounded-md border border-gray-300 px-3 py-2 focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500"
              placeholder="Any specific questions, concerns, or observations to highlight..."
            />
          </div>

          <div className="flex gap-4 border-t border-gray-200 pt-6">
            <button
              type="submit"
              disabled={generating}
              className="rounded-md bg-blue-600 px-6 py-2 text-sm font-medium text-white hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
            >
              {generating ? "Generating..." : "Generate Brief"}
            </button>
            <Link
              href="/dashboard/appointments"
              className="rounded-md border border-gray-300 px-6 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-offset-2"
            >
              Cancel
            </Link>
          </div>
        </form>
      </div>

      <div className="mt-6 rounded-md bg-yellow-50 p-4 text-sm text-yellow-800">
        <p className="font-semibold">💡 What gets included:</p>
        <ul className="mt-2 list-inside list-disc space-y-1">
          <li>All active regimen items with dosages and schedules</li>
          <li>Flagged potential interactions (if any)</li>
          <li>Up to 5 most recent research notes</li>
          <li>Custom notes you add above</li>
          <li>Patient diagnosis and basic information</li>
        </ul>
      </div>
    </div>
  );
}
